<a href="https://colab.research.google.com/github/abernauer/Deep-Learning-with-Python/blob/master/Chapter2_building_blocks_of_neural_nets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.1 A first look at a neural network

In [ ]:
from keras.datasets import mnist
(train_images, train_lables), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 0s 0us/step


 *Training data*

In [ ]:
train_images.shape


(60000, 28, 28)

In [ ]:
len(train_lables)

60000

In [ ]:
train_lables

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

*Testing data*

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
len(test_labels)

10000

In [ ]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

*Network Architechture*

In [ ]:
from keras import models
from keras import layers


In [ ]:
net = models.Sequential()
net.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
net.add(layers.Dense(10, activation='softmax'))

*compilation step*

* A loss function how we measure our performance on the training data
* An optimizer the mechanism in which, the network will update based on the data and loss function
* Metrics to monitor during testing and training in this case accuracy


*Compilation Step*

In [ ]:
net.compile(optimizer='rmsprop',
            loss='categorical_crossentropy',
            metrics=['accuracy'])

*Preparing the data*

In [ ]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

*Preparing the labels*

In [ ]:
from keras.utils import to_categorical

train_lables = to_categorical(train_lables)
test_labels = to_categorical(test_labels)

In [ ]:
net.fit(train_images, train_lables, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 5s 80us/step - loss: 0.2561 - accuracy: 0.9261
Epoch 2/5
60000/60000 [==============================] - 4s 74us/step - loss: 0.1039 - accuracy: 0.9684
Epoch 3/5
60000/60000 [==============================] - 4s 74us/step - loss: 0.0688 - accuracy: 0.9792
Epoch 4/5
60000/60000 [==============================] - 4s 73us/step - loss: 0.0502 - accuracy: 0.9851
Epoch 5/5
60000/60000 [==============================] - 5s 76us/step - loss: 0.0379 - accuracy: 0.9887


The quantities displayed above are the loss and accuracy of the training. 


In [ ]:
test_loss, test_acc = net.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 51us/step


In [ ]:
print("test_acc:", test_acc)

test_acc: 0.9812999963760376


#2.2 Data representations for neural networks

The data in the previous example was stored in a multidimensional Numpy array or *tensors*

A simple explanation of a tensor is a container for data--primarily numeric data. In the context of tensors a *dimension* is often called an *axis*.

# 2.2.1 Scalars (0D tensors)

A 0D tensor containing a only one number is called a *scalar*

In Numpy, a float32 or float64 number is a scalar tensor. The number of axes of a tensor is called it's *rank*.

In [ ]:
import numpy as np
x = np.array(12)
x

array(12)

In [ ]:
x.ndim

0

#2.2.2 Vectors (1D tensors)

*Vector* or 1D tensor is an array of numbers.

A 1D tensor has exactly one axis.

In [ ]:
x = np.array([12, 3, 6, 14, 7])

In [ ]:
x

array([12,  3,  6, 14,  7])

In [ ]:
x.ndim

1

A vector with five entries or elements is a *5-dimensional vector*.
*Dimensionality* can denote the number of entries or elements along a specific axis or the number of axis in a tensor. So a 5D tensor would be a *tensor of rank 5*.


#2.2.3 Matrices (2D tensors)

An array of vectors is a *matrix*, or 2D tensor. A matrix has two axes referred to as *rows* and *columns*.
A visual interpretation of a matrix as a rectangular grid of numbers.

In [ ]:
x = np.array( [[5, 78, 2, 34, 0],
             [6, 79, 3, 35, 1],
             [7, 80, 4, 36, 2]])

In [ ]:
x.ndim

2

The entries from the first axis are called the *rows*, and the elements from the second axis are called the *columns*. [5, 78, 2, 34, 0] is the first row of x and [5, 6, 7] is the first column.

#2.2.4 3D tensors and higher-dimensional tensors

If we pack a matrix in a new array, you obtain a 3D tensor, which you can visually interpret as a cube of numbers. 

In [ ]:
x = np.array([[[5, 78, 2, 34, 0],
                   [6, 79, 3, 35, 1],
                   [7, 80, 4, 36, 2]],
                  [[5, 78, 2, 34, 0],
                   [6, 79, 3, 35, 1],
                   [7, 80, 4, 36, 2]],
                  [[5, 78, 2, 34, 0],
                   [6, 79, 3, 35, 1],
                   [7, 80, 4, 36, 2]]])

In [ ]:
x.ndim

3

Packing 3D tensors in an arrray, you create a 4D tensor. 

#2.2.5 Key attributes 

A tensor is defined by three key attributes:

* *Number of axes (rank)*--For instance, a 3D tensor has three axes, and a matrix has two axes.

* *Shape*-- This is a tuple of intergers that describes how many dimensions the tensor has along each axis.

* *Data type* (called dtype in Python libraries)--This is the type of the data contained in the tensor.